version: '3.8'
services:
  frontend:
    build: ./nextjs-app
    ports:
      - '3000:3000' # Expose frontend on port 3000
    environment:
      - NODEJS_API_URI=backend:5000/api/v1/ai-mermaid # Corrected URI
    depends_on:
      - backend # Ensure backend starts before frontend

  backend:
    build: ./nodejs-api
    ports:
      - '5000:5000' # Expose backend on port 5000
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/ai-mermaid # Updated URI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
    depends_on:
      - mongo # Ensure MongoDB starts before backend

  mongo:
    image: mongo:8 # Use MongoDB version 8
    ports:
      - '27017:27017' # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # Initialize MongoDB

volumes:
  mongo-data: # Define volume for MongoDB data persistence