version: '3.8'
services:
  frontend:
    build: ./nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./nodejs-api
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

