// src/models/chat.js
/**
 * Chat Model
 * 
 * This module defines the Mongoose schema and model for storing chat history.
 * Each document in the `Chat` collection contains:
 * - `userInput`: The input provided by the user.
 * - `mermaidCode`: The Mermaid code generated by the AI.
 * - `timestamp`: The time when the document was created.
 * 
 * Dependencies:
 * - `mongoose`: MongoDB object modeling tool for Node.js.
 */

const mongoose = require("mongoose");

// Define the schema for the Chat collection
const chatSchema = new mongoose.Schema(
  {
    userInput: {
      type: String,
      required: true, // User input is required
    },
    mermaidCode: {
      type: String,
      required: true, // Generated Mermaid code is required
    },
    timestamp: {
      type: Date,
      default: Date.now, // Automatically sets the current time when the document is created
    },
  },
  { timestamps: true } // Adds `createdAt` and `updatedAt` fields automatically
);

// Create the Mongoose model for the Chat collection
const Chat = mongoose.model("Chat", chatSchema);

module.exports = Chat; // Export the Chat model